### ISSUE TITLE
Sort + QuerydslPredicate on CouchbaseRepository results in java.lang.IllegalArgumentException: Sort must not be null

### ISSUE THREAD

**Issue by ocsross** [spring-projects/spring-data-couchbase#1600] opened 2022-10-19 02:32 UTC
Using repository

```
@Repository
public interface TestRepository extends CouchbaseRepository<TestEntity, String>, QuerydslPredicateExecutor<TestEntity>,
        QuerydslBinderCustomizer<TestEntity> {
```

When queried with @QuerydslPredicate Predicate predicate & Pageable pageable that has Sort set I get the following:

```
java.lang.IllegalArgumentException: Sort must not be null
	at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.3.23.jar:5.3.23]
	at org.springframework.data.couchbase.repository.support.BasicQuery.setSort(BasicQuery.java:64) ~[spring-data-couchbase-4.4.5.jar:4.4.5]
	at org.springframework.data.couchbase.repository.support.SpringDataCouchbaseQuery.createQuery(SpringDataCouchbaseQuery.java:265) ~[spring-data-couchbase-4.4.5.jar:4.4.5]
	at org.springframework.data.couchbase.repository.support.SpringDataCouchbaseQuery.createQuery(SpringDataCouchbaseQuery.java:235) ~[spring-data-couchbase-4.4.5.jar:4.4.5]
```

The issue may relate to org.springframework.data.couchbase.repository.support.SpringDataCouchbaseQuerySupport and its method createSort returning a null Sort:

```
protected Sort createSort(List<OrderSpecifier<?>> orderSpecifiers) {
return null; // TODO serializer.toSort(orderSpecifiers);
}

```

**Comment by mikereiche** [comment] 2022-10-19 02:36
duplicate of #1363

**Closed by mikereiche** 2022-10-19 02:36 UTC
Labels: status: duplicate
