### ISSUE TITLE
cas of document replaced in transaction changes again on completion of transaction.  @Transactional method (5.0.0-M6)

### ISSUE THREAD

**Issue by PRodrigues-eb** [spring-projects/spring-data-couchbase#1589] opened 2022-10-12 20:43 UTC
Hi,

We catched a situation in which the @Version field is being updated more than once when we call a `save` inside a @Transactional method.

If we have a @Transactional method like the following:

```
@Transactional
public Account create(Account account) {
   //  ... any logic
   return accountRepository.save(account);
}
```
We noticed that when the caller try to perform any update in the returned object we were receiving an `OptimisticLockingFailureException`.

After some investigation we saw that the @Version field was being updated more than once, the first is when we call the `save` method, and a second is possibly happening after the finish of the @Transactional method execution.

We can reproduce this situation by logging the version after the `save` and logging again on the caller after query the same object.
 
Something like: 

```
@Transactional
public Account create(Account account) {
   //  ... any logic
   Account saved = accountRepository.save(account);
  log.info("Version of saved object {}", saved.getVersion());
  
   return saved;
}
```

```
public void callerMethod() {
   //  ... any logic
   Account saved = accountService.create(new Account());
   Account queried = accountService.findById(saved.getUuid());
   
   log.info("Versions of saved {} and queried {}", saved.getVersion(), queried.getVersion());
}
```

Important to reinforce that it only happens if the `create` is @Transactional, if we remove the @Transactional annotation the @Version field is updated only once and the caller can perform updates over the returned object without any problem.

**Comment by mikereiche** [comment] 2022-10-12 21:08
It would be useful to have a complete reproducer - can you share that in a github repo? Even the complete callerMethod() that gets an OptimisticLockingFailureException would be useful - along with the output (both logging an stacktrace).

At the point where saved.getVersion() is logged in create(), it should not have been set yet. (accountRepository.save(account) doesn't actually save it to couchbase, it just records in the transaction context that this is intended to be done in the transaction). I expect it to be 0 at that point.
```
   //  ... any logic
   ClientOperationsAccount saved = accountRepository.save(account);
  log.info("Version of saved object {}", saved.getVersion());
```
Upon completion of the @Transactional method, account is inserted into couchbase and the returned cas is used to update the @Version.  When the following calls are made, saved.getVersion() will have the new cas, and so will query.getVersion().
```
   ClientOperationsAccount queried = clientOperationsAccountService.findById(saved.getUuid());
   log.info("Versions of saved {} and queried {}", saved.getVersion(), queried.getVersion());
```
A subsequent call to replace(saved) or replace(queried) should succeed as they both have the latest cas in their @Version.

One critical point is that the CouchbaseTransactionInterceptor must be used.  If the (non-Couchbase) TransactionInterceptor

**Comment by PRodrigues-eb** [comment] 2022-10-13 15:22
This is the desired behavior? I think that we naturally expect that this behavior would not vary because the method is @Transactional.

Generate a new cas on the transaction completion is really needed if it was already generated on the `save` operation?

**Comment by mikereiche** [comment] 2022-10-13 15:43
As I mentioned, I am waiting for clarification.  I suspect there is an issue with using data from a transaction outside of that transaction. It would seem to create the possibility of violating transaction isolation. 

> Generate a new cas on the transaction completion is really needed if it was already generated on the save operation?

I assume there are two cas's because of the two-phase-commit nature of the transaction.  The first cas when the replace() is staged and the second cas when the replace() is committed.

**Comment by mikereiche** [comment] 2022-10-14 18:27
The short explanation is that replace()/remove() of an entity object inside a transaction that was obtained outside that transaction is susceptible to write-write conflict from an update outside of that transaction.  Furthermore, without the cas mechanism, such write-write conflicts are undetectable as it's not possible to know if the entity object was read before or after the outside update occurred.   And therefore transactions can(should*) only replace()/remove() entity objects which have been obtained inside the transaction.  So a second transaction using the object output by the first transaction should indeed fail.  

*The behavior that a transaction can use an object obtained outside any transaction is a misbehavior - although it does succeed now and does not cause any inconsistency - **_it should not be used as in the future it may no longer work_**.

Here is the long answer from discussions between the transactions developer and myself.

The java sdk couchbase transactions implementation requires an AttemptContext and a TransactionGetResult (as an input for replace and remove operations).   i.e. ctx.replace(txGetResult, replDoc) and ctx.remove(txGetResult).  The attemptContext is available inside the transaction lambda  and the calling application is responsible for obtaining  the transactionGetResult object  from one call in a transaction and passing it to a subsequent call  in the same transaction.    Spring data entities have no place to hold that TransactionGetResult. At one point I had proposed adding a @TransactionGetResult TransactionGetResult transactionGetResult field (like @Version), but the issue is that transactionGetResult might come from one transaction and be (attempted) to use in a subsequent transaction.  And also this would only work if the entity had a TransactionGetResult defined. I then proposed to hold  TransactionGetResults in a map in either ThreadLocal (for synchronous transactions) or in the reactive context (for reactive transactions).   This would work fine when (a) the TransactionGetResult had been populated (by an insert or a find); and (b) was consumed in the *same* transaction by a replace() or remove().  Although I liked this idea it, was rejected.  The mechanism that was implemented was that whenever a TransactionGetResult was needed in a replace() or remove(), the document would be get()-ed (in the spring-data-couchbase code), and that TransactionGetResult would be used. Although this works, it results in a somewhat duplicate get() if the document was already get()-ed in the transaction by the application.  This internal get() gives the illusion that a document can be replace()-ed or remove()-ed in a transaction where it has not been get()-ed.  It cannot (spring-data-couchbase is doing the get() internally).  If this implementation was replaced by my (favored)  implementation of storing the TransactionGetResult from an application's insert() or get() in a transaction in a map in ThreadLocal or the reactive context - any code written to replace() or update() an entity object in a transaction that was obtained outside the transaction - would fail, as it does not have a TransactionGetResult from the current transaction.

**Closed** 2022-11-01 17:50 UTC
Labels: status: feedback-provided

**Comment by mikereiche** [comment] 2022-11-01 17:54
Following the discussion - the document replaced in a transaction needs to have had in that same transaction an operation that obtained the cas (insert/replace/get).    A cas from outside the transaction (including from inside a previous transaction)  is "out-of-date". 
Likewise, outside of a transaction, the cas from inside a prior transaction is "out-of-date".
